# Route 1
user_new:
    path:     /users
    defaults: { _controller: "AppBundle:User:new" }
    methods:  POST

# Route 5
user_index:
    path:     /users
    defaults: { _controller: "AppBundle:User:index" }
    methods:  GET

# Route 6
user_search:
    path:     /users/search
    defaults: { _controller: "AppBundle:User:search" }

# Route 4
user_show:
    path:     /user/{id}
    defaults: { _controller: "AppBundle:User:show" }
    methods:  GET

# Route 2
user_edit:
    path:     /user/{id}
    defaults: { _controller: "AppBundle:User:edit" }
    methods:  PUT

# Route 3
user_delete:
    path:     /user/{id}
    defaults: { _controller: "AppBundle:User:delete" }
    methods:  DELETE

# bad route
user_users_bad:
    path:     /users
    defaults: { _controller: "AppBundle:User:bad" }
user_show_bad:
    path:     /user/{id}
    defaults: { _controller: "AppBundle:User:bad" }