AppBundle\Entity\User:
    type: entity
    table: user
    uniqueConstraints:
        mail:
            columns:
                - email
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        lastname:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
        firstname:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
        email:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
        password:
            type: string
            nullable: false
            length: 40
            options:
                fixed: false
        role:
            type: string
            nullable: false
            length: null
            options:
                fixed: false
    lifecycleCallbacks: {  }
